// userActions
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const RESET_PASSWORD_START = "RESET_PASSWORD_START";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const SIGN_OUT_USER_START = "SIGN_OUT_USER_START";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR";

export const ON_AUTH_START = "ON_AUTH_START";
export const ON_AUTH_SUCCESS = "ON_AUTH_SUCCESS";
export const ON_AUTH_FAIL = "ON_AUTH_FAIL";

// foodActions
export const FETCH_ALL_FOOD_START = "FETCH_ALL_FOOD_START";
export const FETCH_ALL_FOOD_SUCCESS = "FETCH_ALL_FOOD_SUCCESS";
export const FETCH_ALL_FOOD_ERROR = "FETCH_ALL_FOOD_ERROR";

export const ADD_FOOD_START = "ADD_FOOD_START";
export const ADD_FOOD_SUCCESS = "ADD_FOOD_SUCCESS";
export const ADD_FOOD_ERROR = "ADD_FOOD_ERROR";

// recipeActions
export const FETCH_ALL_RECIPE_START = "FETCH_ALL_RECIPE_START";
export const FETCH_ALL_RECIPE_SUCCESS = "FETCH_ALL_RECIPE_SUCCESS";
export const FETCH_ALL_RECIPE_ERROR = "FETCH_ALL_RECIPE_ERROR";

export const ADD_RECIPE_START = "ADD_RECIPE_START";
export const ADD_RECIPE_SUCCESS = "ADD_RECIPE_SUCCESS";
export const ADD_RECIPE_ERROR = "ADD_RECIPE_ERROR";

export const FETCH_FOOD_NAMES_START="FETCH_FOOD_NAMES_START";
export const FETCH_FOOD_NAMES_SUCCESS="FETCH_FOOD_NAMES_SUCCESS";
export const FETCH_FOOD_NAMES_ERROR="FETCH_FOOD_NAMES_ERROR";